---

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  when: nginx_service_state != 'stopped'

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  when: nginx_service_state != 'stopped'
